### ISSUE TITLE
Feature (Frontend): Implementación del componente Recomendaciones

### ISSUE THREAD

**Issue by moisesnks** [TSSW2024/sprint-1#10]
## Descripción
En este issue nos enfocaremos en la implementación del componente Recomendaciones en la vista Home de la aplicación. El componente Recomendaciones mostrará sugerencias, descuentos o promociones provenientes de la marca, utilizando un mockup en lugar de datos reales del servidor.

## Requerimientos
El componente Recomendaciones debe cumplir con los siguientes requisitos:

- [x] **Text: Título del Anuncio**: Debe mostrar el título del anuncio.
- [x] **Text: Subtítulo**: Debe mostrar el subtítulo del anuncio.
- [x] **Icon**: Debe mostrar un icono asociado al anuncio.
- [x] **Distribución de Elementos**: Los elementos (título, subtítulo e icono) deben distribuirse como se describe a continuación:
  - [x] Título, Subtítulo y Icono deben estar en un contenedor como filas.
  - [x] Título y Subtítulo deben estar en un contenedor como columnas y ocupar el 80% del ancho.
  - [x] El Icono debe ocupar el 20% restante del ancho.
- [x] **Mockup de Datos**: Se deben utilizar datos de ejemplo para simular la respuesta del servidor. Se proporciona un ejemplo de cómo podrían estructurarse los datos en forma de array de objetos.

```dart
final List<Map<String, String>> data = [
  {
    "titulo": "¡No gastes de más!",
    "subtitulo": "Aprovecha esta promoción",
    "icono": "http://google.com/images/icono1.png"
  },
  {
    "titulo": "¡Descuento especial!",
    "subtitulo": "Solo por tiempo limitado",
    "icono": "http://google.com/images/icono2.png"
  },
  {
    "titulo": "¡Oferta exclusiva!",
    "subtitulo": "No te lo pierdas",
    "icono": "http://google.com/images/icono3.png"
  }
];
```

## Tareas
- [x] Implementar el componente Recomendaciones en la vista Home.
- [x] Agregar el título del anuncio y el subtítulo.
- [x] Mostrar el icono asociado al anuncio.
- [x] Configurar la distribución de los elementos de acuerdo a las especificaciones.
- [x] Utilizar el mockup de datos proporcionado para simular la respuesta del servidor.
- [x] Realizar pruebas para asegurar el correcto funcionamiento y apariencia del componente.

## Rama Asignada
Este issue debe ser desarrollado en una rama aparte llamada `1-feature-recomendaciones`.

## Fecha de Vencimiento
Este issue debe ser completado antes del 20/4/2024.

**Comment by zkodah** [comment]
¿Como va?
