### ISSUE TITLE
Feature (Frontend): Implementación del componente ListaMonedas

### ISSUE THREAD

**Issue by moisesnks** [TSSW2024/sprint-1#11]
## Descripción
En este issue nos enfocaremos en la implementación del componente ListaMonedas en la vista Home de la aplicación. El componente ListaMonedas se encarga de renderizar una lista de monedas con su valor y ratio de cambio, utilizando datos proporcionados por el servidor.

## Requerimientos
El componente ListaMonedas debe cumplir con los siguientes requisitos:

- [ ] **Filtros en la parte Superior**: Debe mostrar una barra TopBar en la parte superior del componente con tres filtros: Top, Top decliners y Nuevos.
- [ ] **Lista de Elementos**: Debe renderizar los elementos como una lista debajo de los filtros, cada uno con los siguientes detalles:
  - [ ] **Text**: Nombre de la moneda.
  - [ ] **Text**: Valor de la moneda.
  - [ ] **Text**: Ratio de cambio.

## Tareas
- [ ] Implementar la barra de filtros en la parte superior del componente.
- [ ] Renderizar la lista de elementos de acuerdo a los datos proporcionados por el servidor.
- [ ] Mostrar el nombre, valor y ratio de cambio de cada moneda en la lista.
- [ ] Realizar pruebas para asegurar el correcto funcionamiento y apariencia del componente.

## Rama Asignada
Este issue debe ser desarrollado en una rama aparte llamada `1-feature-listamonedas`.

## Fecha de Vencimiento
Este issue debe ser completado antes del 20/4/2024.

## Ejemplo de Uso
Se proporciona un ejemplo de datos en JavaScript para ilustrar la estructura esperada:

```dart
const data = [
    {
        "moneda": "BTC",
        "value": 69350.08,
        "ratio": -1.0900
    },
    {
        "moneda": "ETH",
        "value": 2350.67,
        "ratio": 0.7600
    },
    {
        "moneda": "LTC",
        "value": 182.54,
        "ratio": 2.1500
    }
];
```

Puedes encontrar un ejemplo con este mockup en [este repositorio en Svelte](https://github.com/SmnZin/example).

**Comment by zkodah** [comment]
¿Como va?

**Comment by SmnZin** [comment]
ta listo jefe
