### ISSUE TITLE
Feature (Frontend): Implementación del Navbar

### ISSUE THREAD

**Issue by moisesnks** [TSSW2024/sprint-1#12]
## Descripción
En este issue nos enfocaremos en la implementación del componente Navbar, que estará presente en todas las vistas principales de la aplicación. El Navbar contendrá tres elementos con iconos y títulos, que permitirán la navegación a diferentes secciones de la aplicación.

## Requerimientos
El componente Navbar debe cumplir con los siguientes requisitos:

- [x] **Elemento Mercado**: Debe tener un icono de Gráfico de Barras y redireccionar a la vista Mercado.
- [x] **Elemento Descubrir**: Debe tener un icono de Diamante y redireccionar a la vista Descubrir.
- [x] **Elemento Carteras**: Debe tener un icono de Billetera y redireccionar a la vista Carteras.

## Tareas
- [x] Implementar el componente Navbar en todas las vistas principales de la aplicación.
- [x] Agregar los elementos correspondientes para Mercado, Descubrir y Carteras con sus respectivos iconos y títulos.
- [x] Configurar la redirección adecuada para cada elemento del Navbar.
- [x] Estilizar el Navbar para que se vea coherente en todas las vistas.

## Rama Asignada
Este issue debe ser desarrollado en una rama aparte llamada `1-feature-navbar`.

## Fecha de Vencimiento
Este issue debe ser completado antes del 20/4/2024.

**Comment by zkodah** [comment]
¿Como va?
