### ISSUE TITLE
Feature (Frontend): Inicio de Sesión

### ISSUE THREAD

**Issue by moisesnks** [TSSW2024/sprint-1#5]
### Descripción
Este issue se enfoca en implementar la vista de inicio de sesión en la aplicación. La vista constará de un formulario donde los usuarios podrán ingresar su nombre de usuario y contraseña. Además, se implementará la lógica de validación del inicio de sesión, que redireccionará a los usuarios a la vista Home si las credenciales son correctas.

### Tareas
- [x] Implementar un campo de texto para el nombre de usuario (TextField: Username).
- [x] Implementar un campo de texto para la contraseña (TextField: Password).
- [x] Implementar un botón de envío para iniciar sesión (Button: Submit).
- [x] Agregar un enlace de texto para "Olvidaste tu contraseña".
- [x] Implementar la función de validación de inicio de sesión utilizando la lógica proporcionada o algo similar.
- [x] Redireccionar a los usuarios a la vista Home si las credenciales son válidas.

### Lógica sugerida:
```dart
bool validate(String user, String password) {
  if (user == "admin@utem.cl" && password == "12345") {
    return true;
  }
  return false;
}
```
Esta función toma dos parámetros, user y password, y devuelve true si coinciden con las credenciales de inicio de sesión de prueba ("admin@utem.cl" y "12345"). De lo contrario, devuelve false.

> Esta implementación es básica, porque se espera poder moverse entre las pantallas nada más, ya que la verdadera lógica de autenticación vendrá en los siguientes sprints.

### Rama Asignada
Este issue debe ser desarrollado en una rama aparte llamada `1-feature-login`.

### Fecha de Vencimiento
Este issue debe ser completado antes del 20/4/2024.

**Comment by zkodah** [comment]
¿Como va?

**Comment by Vatelfil** [comment]
bien, estoy editando y agregando la conexión con google, face, etc
