### ISSUE TITLE
Feature (Frontend): Registro de usuario

### ISSUE THREAD

**Issue by moisesnks** [TSSW2024/sprint-1#6]
### Descripción
En esta funcionalidad, se desarrollará la vista y el formulario de registro de usuario en el frontend de la aplicación. El formulario recopilará información importante del usuario, como nombre, correo electrónico, contraseña, fecha de nacimiento y número de documento. Además, se incluirá la funcionalidad para aceptar los términos y condiciones antes de confirmar el registro.

### Formulario
- [x] **TextField**: Nombre
- [x] **TextField**: Correo electrónico *(con validación)*
- [x] **TextField**: Contraseña
- [x] **DatePicker**: Fecha de nacimiento
- [x] **TextField**: Número de documento
- [x] **Términos y Condiciones**: Al hacer clic, se mostrará un overlay con los términos y condiciones.
- [x] **Botón**: Confirmar registro, que guardará los datos del formulario y los imprimirá en la consola.

#### Se espera que el botón de **Confirmar** guarde un objeto, que sea así, por ejemplo:
```dart
var userData = UserData(
    name: "John Doe",
    email: "johny@foo.cl",
    password: "5f4dcc3b5aa765d61d8327deb882cf99",
    date: DateTime.utc(2024, 4, 1, 15, 30, 0),
    rut: "1234567-8",
    acceptTerms: true,
);
```

## Detalles de Términos y Condiciones
- [x] Al hacer clic en el texto, se mostrará un overlay con los términos y condiciones.
- [x] El overlay mostrará un texto largo, como "Lorem ipsum...", y un botón para confirmar los términos.
- [x] Se manejará una variable `isAccepted` que indicará si se aceptaron o no los términos.

## Tareas
- [x] Implementar la vista y el formulario de registro de usuario.
- [x] Validar el campo de correo electrónico para garantizar un formato correcto.
- [x] Implementar la lógica para mostrar y aceptar los términos y condiciones.
- [x] Conectar el botón de confirmar registro con la lógica para guardar los datos y mostrarlos en la consola.

## Rama Asignada
Este issue debe ser desarrollado en una rama aparte llamada 1-feature-register.

### Fecha de Vencimiento
Este issue debe ser completado antes del 20/4/2024.

> Observación
La contraseña debe ser almacenada de forma segura, preferiblemente hasheada, por motivos de seguridad.

**Comment by ItaloRojas** [comment]
esta listo pero no pude poner los tickets

**Comment by zkodah** [comment]
El diseño este en el figma. en ese te puedes basar, los colores están aun por determinar
