### ISSUE TITLE
Feature (Frontend): Implementación del TopBar en Home

### ISSUE THREAD

**Issue by moisesnks** [TSSW2024/sprint-1#8]
## Descripción
En este issue nos enfocaremos en la implementación del componente TopBar en la vista Home de la aplicación. El TopBar es un elemento esencial que proporciona acceso rápido a diferentes secciones de la aplicación, como Ajustes, Búsqueda de Monedas y Acerca de Nosotros.

## Requerimientos
El componente TopBar debe cumplir con los siguientes requisitos:

- [x] **Icono de la Aplicación**: Este icono debe redireccionar a la vista de Ajustes cuando se hace clic en él.
- [x] **Icono de Búsqueda**: Este icono debe redireccionar a la vista de Buscar Monedas cuando se hace clic en él.
- [x] **Icono de Acerca de Nosotros**: Este icono debe redireccionar a la vista de Acerca de Nosotros cuando se hace clic en él.

## Tareas
- [x] Implementar el componente TopBar en la vista Home.
- [x] Agregar los iconos correspondientes para Ajustes, Búsqueda de Monedas y Acerca de Nosotros.
- [x] Configurar la redirección adecuada para cada icono.
- [x] Realizar pruebas para garantizar el correcto funcionamiento del componente.

## Rama Asignada
Este issue debe ser desarrollado en una rama aparte llamada `1-feature-topbar`.

## Fecha de Vencimiento
Este issue debe ser completado antes del 20/4/2024.

> Observación: se espera la redirección a nuevas ventanas **(Scaffold)** pero no se espera el desarrollo de estas, sólo que estén ahí y tengan un título al menos.

**Comment by zkodah** [comment]
¿Como va?
