### ISSUE TITLE
Feature (Frontend): Implementación del componente Saldo en Home

### ISSUE THREAD

**Issue by moisesnks** [TSSW2024/sprint-1#9]
## Descripción
En este issue nos enfocaremos en la implementación del componente Saldo en la vista Home de la aplicación. El componente Saldo informa al usuario sobre su Saldo Total y proporciona la funcionalidad para mostrar u ocultar el saldo.

## Requerimientos
El componente Saldo debe cumplir con los siguientes requisitos:

- [x] **Text: Título**: El título debe decir "Saldo Total".
- [x] **Icon**: Debe contar con un ícono que pueda cambiar entre el icono del ojo abierto (eye) y el ojo cerrado (eye slash).
- [x] **Toggle del Icono**: Al hacer clic en el ícono, se debe cambiar entre el icono del ojo abierto y el ojo cerrado.
- [x] **Estado isVisible**: El componente debe manejar un estado llamado isVisible para controlar la visibilidad del saldo.
- [x] **Text: Saldo**: Debe mostrar el saldo total. Si el estado isVisible es false, el saldo debe mostrarse visualmente como ********. Si el estado isVisible es true, se debe mostrar el saldo formateado a la moneda chilena.
- [x] **Button: Botón Depositar**: Debe ser un botón que redirige al usuario a la vista Depositar.

## Tareas
- [x] Implementar el componente Saldo en la vista Home.
- [x] Agregar el título "Saldo Total".
- [x] Incorporar un icono que cambie entre el icono del ojo abierto y el ojo cerrado.
- [x] Configurar la funcionalidad para cambiar el estado isVisible al hacer clic en el icono.
- [x] Mostrar el saldo de acuerdo al estado isVisible y formatearlo a la moneda chilena cuando sea necesario.
- [x] Agregar el botón "Depositar" y configurar la redirección a la vista correspondiente.

## Rama Asignada
Este issue debe ser desarrollado en una rama aparte llamada `1-feature-saldo`.

## Fecha de Vencimiento
Este issue debe ser completado antes del 20/4/2024.

**Comment by zkodah** [comment]
¿Como va?

**Comment by moisesnks** [comment]
@armitage6 Excelente implementación! estaba revisándola y me gustó mucho. Está muy bien.
